openapi: 3.0.0
info:
  title: Payments Service
  description: Handles payment processing and transactions.
  x-cortex-tag: payments-service
  x-cortex-type: service
  x-cortex-groups:
    - financial-systems
  x-cortex-owners:
    - type: group
      name: cortex-workshops/payments-team
      provider: GITHUB
  x-cortex-link:
    - name: README
      type: docs
      url: https://github.com/cortex-workshops/payment-service#readme
  x-cortex-git:
    github:
      alias: cortex
      repository: cortex-workshops/payments-service
